apiVersion: v1
kind: Namespace
metadata:
  name: dev
-----
kind: Deployment
apiVersion: v1
metadata:
    name: springbootdemo
    namespace: dev
spec:
    replicas: 1
    template:
        metadata:
            name: springbootdemo
        spec:
            containers: [{name: springbootdemo, image: 'sinhaabhinav1991.azurecr.io/abhinavsinha1991/spring-boot-demo:latest', resources: {requests: {cpu: '1', memory: 1Gi}}, terminationMessagePath: /dev/termination-log, terminationMessagePolicy: File, imagePullPolicy: Always, securityContext: {privileged: false, procMount: Default},
                imagePullSecrets:[{name: acrsecret}]}]
            restartPolicy: Always
            terminationGracePeriodSeconds: 30
            dnsPolicy: ClusterFirst
