apiVersion: v1
kind: NameSpace
metdata:
	name: #{Build.EnvironmentName}#
-----
apiVersion: apps/v1beta1
kind: Deployment
metadata:
	name: springbootdemo
	namespace: #{Build.EnvironmentName}#
spec:
	replicas: #{Build.SpringBootDemo.Replicas}#
	template:
		metadata:
			labels:
				app: springbootdemo
		spec:
			containers:
			- image: 
			  name: springbootdemo
			  ports: 
			  - containerPort: 8080
			imagePullSecrets:
			- name: acrsecret
-----
apiVersion: v1
kind: Service
metadata:
	name: springbootdemo
	namespace: #{Build.EnvironmentName}#
spec:
	ports:
	- port:80
	  protocol: TCP
	  targetPort: 8080
	selector:
		app: springbootdemo
	type: ClusterIP
-----
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
	name: springbootdemo
	annotations:
		kubernetes.io/ingress.class: addon-http-application-routing
spec:
	rules:
	- host: springbootdemo.de3efeef8a094b89898c.southindia.aksapp.io
	  http:
		paths:
		- backend:
			serviceName: springbootdemo
			servicePort: 80
		  path: /	
